version: "3.9"

services:
  homeassistant:
    privileged: true
    environment:
      TZ: Europe/Berlin
    volumes:
      - /etc/homeassistant/config:/config
    network_mode: "host"
    image: ghcr.io/home-assistant/home-assistant:stable
    deploy:
      restart_policy:
        condition: on-failure